add gamescope wrapper script and volume changer

diff --git a/.local/bin/gpufan b/.local/bin/gpufan
--- a/.local/bin/gpufan
+++ b/.local/bin/gpufan
@@ -1,76 +1,121 @@
 #!/usr/bin/env bash
 
-temp_input=/sys/class/drm/card0/device/hwmon/[[:print:]]*/temp1_input
-pwm1=/sys/class/drm/card0/device/hwmon/[[:print:]]*/pwm1
-pwm1_enable=/sys/class/drm/card0/device/hwmon/[[:print:]]*/pwm1_enable
+temp_input=("/sys/class/drm/card"[[:digit:]]"/device/hwmon/"[[:print:]]*"/temp1_input")
+pwm1=("/sys/class/drm/card"[[:digit:]]"/device/hwmon/"[[:print:]]*"/pwm1")
+pwm1_enable=("/sys/class/drm/card"[[:digit:]]"/device/hwmon/"[[:print:]]*"/pwm1_enable")
 
-change_speed()
+percentage='0'
+pwm_value='0'
+
+usage()
 {
-    if [[ $1 -lt 0 || $1 -gt 100 ]]; then
-        echo "Value given must be between 0 and 100."
-    else
-        pwm_value=$(echo "scale=2;$1 * 2.55" | bc | awk '{printf "%d", $1}')
-        echo "Converted $1 to $pwm_value."
-        echo "Now setting fan speed to $1% speed..."
-        echo "$pwm_value" | sudo tee -a $pwm1
-    fi
+    cat <<EOF
+Script to change GPU fan speed.
+Enter the percentage of the desired PWM value.
+p: Fan speed percentage between 0 and 100. This will be converted to a PWM value.
+r: Get current speed.
+d: Daemonize script to respond to GPU temperature and change speed accordingly.
+h: Help.
+EOF
 }
 
-check_mode()
+get_pwm_from_percent()
 {
-    if [[ "$(cat $pwm1_enable)" == "1" ]]; then
-            change_speed "$1"
+    echo "scale=2;$percentage * 2.55" | bc | awk '{ printf "%d", $1 }'
+}
+
+get_percent_from_pwm()
+{
+    echo "scale=2;($pwm_value / 255) * 100" | bc | awk '{ printf "%d", $1 }'
+}
+
+get_speed()
+{
+    echo "Current GPU fan speed is: $(get_percent_from_pwm "$pwm_value")%"
+    exit 0
+}
+
+enable_fan()
+{
+    if [[ "$(head "${pwm1_enable[0]}")" == "1" ]]; then
+            change_speed "$percentage"
     else
         echo -n "The GPU fan is currently in automatic mode. Would you like to change it to manual mode? y/n "
         read -r choice
 
         if [[ $choice == "y" ]]; then
             echo "Setting fan to manual mode..."
-            echo 1 | sudo tee -a $pwm1_enable
-            change_speed "$1"
+            echo 1 | sudo tee -a "${pwm1_enable[0]}"
         else
-            echo "Ending script."
+            echo "Keeping fan in automatic mode."
             exit 0
         fi
     fi
 }
 
-if [[ $1 == "-h" || $1 == "--help" ]]; then
-    echo "Script to edit the graphics card fan speed."
-    echo "Enter a PWM value (between 0 and 100) and the speed will be altered."
-    exit 0
-fi
+change_speed()
+{
+    if [[ "$percentage" -lt 0 || "$percentage" -gt 100 ]]; then
+        echo "Value given must be between 0 and 100."
+    else
+        pwm_value="$(get_pwm_from_percent "$percentage")"
+        echo "Converted $percentage to $pwm_value."
+        echo "Now setting fan speed to $percentage% speed..."
+        echo "$pwm_value" | sudo tee -a "${pwm1[0]}"
+    fi
+}
 
-if [[ $1 == "-r" || $1 == "--read" ]]; then
-    percentage=$(cat "$pwm1")
-    echo "Current GPU fan speed is: $(echo "scale=2;$percentage / 2.55" | bc | awk '{printf "%d", $percentage}')%"
-    exit 0
-fi
+daemonize()
+{
+    set -x
+    tcurve="$(readarray -td',' <<<"$(head -n1 ~/.config/gpufan/config)")"
+    fcurve="$(readarray -td',' <<<"$(tail -n2 ~/.config/gpufan/config | tr -d '\n')")"
 
-if [[ $1 == "-d" || $1 == "--daemonize" ]]; then
-    fcurve=$(head -n1 ~/.config/gpufan/config)
-    tcurve=$(tail -n2 ~/.config/gpufan/config | tr -d '\n')
+    while :; do
+        sleep 5
+        temp=$(bc < "${temp_input[0]}")
 
-    readarray -td, farray <<< "$fcurve"; unset "farray[-1]"; declare -p farray;
-    readarray -td, tarray <<< "$tcurve"; unset "tarray[-1]"; declare -p tarray;
-
-    while :; do 
-        sleep 5 
-        temp=$(cat "$temp_input" | bc)
-        
-        for t in "${!tarray[@]}"
-        do 
-            echo "$t ${tarray[t]} ${farray[t]}"
-            if [[ ${temp::-3} -eq "$t" ]]; then 
-                check_mode "${farray[t]}" 
+        for t in "${!tcurve[@]}"; do
+            cat<<-EOF
+            temp: ${tcurve[$t]}
+            fanspeed: ${fcurve[$t]}
+EOF
+            if [[ ${temp::-3} -eq "${tcurve[$t]}" ]]; then
+                change_speed "${fcurve[$t]}"
             fi
-        done 
-    done 
+        done
+    done
+}
 
-fi
-
-if [[ $1 =~ ^[0-9]+$ ]]; then 
-    check_mode "$@"
-fi 
-
-
+while getopts 'p:drh' arg; do
+    case "$arg" in
+        p)
+            percentage="$OPTARG"
+            if [[ "$percentage" =~ ^[0-9]+$ ]]; then
+                enable_fan
+                change_speed "$percentage"
+            else
+                echo "Invalid percentage value."
+                usage
+                exit 1
+            fi
+            ;;
+        d)
+            # nohup daemonize & &>/dev/null disown
+            daemonize
+            ;;
+        r)
+            pwm_value="$(head "${pwm1[0]}")"
+            get_speed
+            ;;
+        h)
+            usage
+            exit 0
+            ;;
+        *)
+            echo "Invalid argument."
+            usage
+            exit 1
+            ;;
+    esac
+done
